# Generated by Django 4.0.5 on 2022-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0002_rename_post_rating_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='I love this Expo!', max_length=50),
        ),
    ]
